export const ACTION_TYPES = {
    GAME_HOST_REQUESTED: "GAME_HOST_REQUESTED",
    GAME_HOSTED: "GAME_HOSTED",
    GAME_JOINED: "GAME_JOINED",
    GAME_UPDATED: "GAME_UPDATED",
    GAME_STARTED: "GAME_STARTED",
    GAME_INPUT_CHANGED: "GAME_INPUT_CHANGED",
    WORD_SUBMITTING: "WORD_SUBMITTING",
    WORD_SUBMITTED: "WORD_SUBMITTED",
    GAME_ENDING: "GAME_ENDING",
    GAME_ENDED: "GAME_ENDED"
}