export const ACTION_TYPES = {
    GAME_HOST_REQUESTED: "GAME_HOST_REQUESTED",
    GAME_HOSTED: "GAME_HOSTED",
    GAME_JOINED: "GAME_JOINED",
    GAME_UPDATED: "GAME_UPDATED",
    GAME_STARTED: "GAME_STARTED"
}